### ISSUE TITLE
Pod  SwipeCellKit is not available

### ISSUE THREAD

**Issue by K-Be** [Aecasorg/WoWilvlChecker#2]
repository  https://github.com/SwipeCellKit/SwipeCellKit.git' does not have a public branch named  "swift_4.2"

pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift_4.2'

**Comment by Aecasorg** [comment]
Updated everything now. Should work hopefully.

**Comment by K-Be** [comment]
I'll look at this tonight.
